version: '3.5'
services:
  go-app:
    container_name: go-app
    build: .
    command: 'sh -c "cd main/core &&  go build -o /core && /core"'
    ports:
      - '8080:8080'
    volumes:
      - ./:/go/src
    working_dir: /go/src
    networks:
      - fullstack


      
  postgres:
    image: postgres:latest
    container_name: full_db
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST} 
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - fullstack
volumes:
  database_postgres:

# Networks to be created to facilitate communication between containers
networks:
  fullstack:

# "datasourceName": "postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable",