version: '3.5'
services:
  go-app:
    container_name: go-app
    # build: .
    image: golang:alpine
    command: sh -c "go run main.go"
    volumes:
      - ./:/go/src/app
    working_dir: /go/src/app
